version: '3.7'

services:

  cisco-dev:
    container_name: cisco-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '1337:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DEV=true